"""
Django settings for ICT4EVENTS project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

from django.contrib import messages

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%c8j8hgg29u86f202d$&!h4n^vcm$!!)p)b0s-jbl4bg3%gjz&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATE_INPUT_FORMATS = [
    "%d/%m/%Y"
]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'crispy_forms',
    'social.apps.django_app.default',
    'rest_framework',
    'events',
    'accounts',
    'sharing',
    'reservations',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap3.backends.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
    'social.backends.twitter.TwitterOAuth',
)

FILE_UPLOAD_HANDLERS = (
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
)

ROOT_URLCONF = 'ICT4EVENTS.urls'

TEMPLATE_LOADERS = (
    'django.template.loaders.sharing.templatetags.file_field',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ICT4EVENTS.preprocessors.base'
            ],
        },
    },
]

WSGI_APPLICATION = 'ICT4EVENTS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'pts2',
        'USER': 'david',
        'PASSWORD': 'TVnuFxx250',
        'HOST': 'ldap.terarion.com',
        'PORT': '5432'
    }
}

# make sure to use sqlite when testing

if 'test' in sys.argv or 'test_coverage' in sys.argv:  # Covers regular testing and django-coverage
    DATABASES['default'] = {'ENGINE': 'django.db.backends.sqlite3'}

orcl = {
    'ENGINE': 'django.db.backends.oracle',
    'NAME': 'XE',
    'USER': 'toets2',
    'PASSWORD': 'test',
    'HOST': 'localhost',
    'PORT': '1521',
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'nl-nl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'statics'),
)

MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger'
}


# Managing login urls
LOGIN_URL = "account:login"
LOGIN_REDIRECT_URL = "events:index"
LOGOUT_REDIRECT_URL = "events:index"

# Social auth
SOCIAL_AUTH_TWITTER_KEY = 'TPCyOZBq49Sje3qr3txoc8FVL'
SOCIAL_AUTH_TWITTER_SECRET = 'pnMSAx1HKZmoUydhF0IG4zH3nJu4FuFFpmp8dBbhD5fAkendSx'

# LDAP Auth

AUTH_LDAP_URI = 'ldap://ldap.terarion.com:389'
AUTH_LDAP_BASE_DN = 'cn=users,dc=test,dc=com'
AUTH_LDAP_BIND_TEMPLATE = "uid={username},cn=users,dc=test,dc=com"

# Crispy Forms

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Handle media uploads

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Email configs

EMAIL_HOST = 'box.terarion.com'
EMAIL_HOST_USER = 'ICT4EVENTS@terarion.com'
EMAIL_HOST_PASSWORD = 'testtest'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
