language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
script:
  - python manage.py test